# theme
import = ["~/.config/alacritty/themes/dracula/theme.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.7
padding = { x = 3, y = 3 }
dynamic_padding = true


[font]
size = 8.0
offset = { x = 1, y = 0 }

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

# [shell]
# program = "/usr/bin/tmux"
# args = ["new-session"]




[cursor]
style = "Beam"
